/**
 * Softmaxxer Product Catalog v1
 * 30-product starter catalog with real brands and comprehensive specifications
 * Sprint 18: Canonical product database for deterministic recommendation engine
 */

import type { ProductSpec } from "@/types/product";

export const CATALOG_V1: ProductSpec[] = [
  // CLEANSERS (6)
  {
    id: "cerave-hydrating-cleanser",
    brand: "CeraVe",
    productName: "Hydrating Cleanser",
    fullName: "CeraVe Hydrating Cleanser",
    role: "cleanser",
    category: "cleanser_gentle",
    priceAUD: 22,
    size: "236ml",
    purchaseUrl: null,
    affiliateUrl: null,
    imageUrl: "/pack1/b7a96626-ea93-49c6-bd8d-e6a73d796c21.png",
    keyActives: ["ceramides", "hyaluronic acid", "glycerin"],
    ingredientNotes: ["non-foaming", "barrier-supportive", "low-irritation profile"],
    freeFrom: ["fragrance"],
    sensitivity: { good: ["reactive", "moderate"], okay: ["resilient"] },
    breakout: { good: ["rare", "occasional"], okay: ["frequent", "persistent"] },
    oiliness: { good: ["dry", "balanced"], okay: ["oily_tzone"], avoid: ["oily_all"] },
    hydration: { good: ["high"], okay: ["low"] },
    routineTime: { good: ["easy", "manageable", "too_much"] },
    concernTargets: ["dryness", "redness", "barrier", "dehydration"],
    barrierFriendly: true,
    pregnancyCaution: false,
    fragranceFree: true,
    essentialOilFree: true,
    alcoholFree: true,
    textureWeight: "medium",
    finish: "natural",
    intensity: "low",
    experienceLevel: "beginner",
    dayPreferred: false,
    nightPreferred: false,
    amAllowed: true,
    pmAllowed: true,
    requiresSpf: false,
    incompatibleWith: [],
    cautionNotes: ["May feel too gentle for very oily skin or heavy sunscreen removal."],
    tags: ["gentle", "hydrating", "barrier-safe", "beginner"]
  },
  {
    id: "lrp-toleriane-hydrating-gentle-cleanser",
    brand: "La Roche-Posay",
    productName: "Toleriane Hydrating Gentle Cleanser",
    fullName: "La Roche-Posay Toleriane Hydrating Gentle Cleanser",
    role: "cleanser",
    category: "cleanser_gentle",
    priceAUD: 30,
    size: "200ml",
    purchaseUrl: null,
    affiliateUrl: null,
    imageUrl: "/pack1/b7a96626-ea93-49c6-bd8d-e6a73d796c21.png",
    keyActives: ["niacinamide", "ceramide-3", "glycerin"],
    ingredientNotes: ["reactive-skin oriented", "minimalist cleanser profile"],
    freeFrom: ["fragrance"],
    sensitivity: { good: ["reactive", "moderate"], okay: ["resilient"] },
    breakout: { good: ["rare", "occasional"], okay: ["frequent"] },
    oiliness: { good: ["dry", "balanced"], okay: ["oily_tzone"], avoid: ["oily_all"] },
    hydration: { good: ["high"], okay: ["low"] },
    routineTime: { good: ["easy", "manageable", "too_much"] },
    concernTargets: ["redness", "dryness", "barrier", "dehydration"],
    barrierFriendly: true,
    pregnancyCaution: false,
    fragranceFree: true,
    essentialOilFree: true,
    alcoholFree: true,
    textureWeight: "medium",
    finish: "natural",
    intensity: "low",
    experienceLevel: "beginner",
    dayPreferred: false,
    nightPreferred: false,
    amAllowed: true,
    pmAllowed: true,
    requiresSpf: false,
    incompatibleWith: [],
    cautionNotes: ["Best used as a barrier-safe baseline cleanser."],
    tags: ["reactive-skin", "barrier-safe", "gentle", "niacinamide"]
  },
  {
    id: "cerave-foaming-facial-cleanser",
    brand: "CeraVe",
    productName: "Foaming Facial Cleanser",
    fullName: "CeraVe Foaming Facial Cleanser",
    role: "cleanser",
    category: "cleanser_gel",
    priceAUD: 22,
    size: "236ml",
    purchaseUrl: null,
    affiliateUrl: null,
    imageUrl: "/pack1/b9314b59-63a0-4058-aaba-9a7fa62ac694.png",
    keyActives: ["niacinamide", "ceramides"],
    ingredientNotes: ["foaming gel format", "better for oilier profiles"],
    freeFrom: ["fragrance"],
    sensitivity: { good: ["resilient", "moderate"], okay: ["reactive"] },
    breakout: { good: ["occasional", "frequent", "persistent"], okay: ["rare"] },
    oiliness: { good: ["oily_tzone", "oily_all", "balanced"], okay: ["dry"] },
    hydration: { good: ["low"], okay: ["high"] },
    routineTime: { good: ["easy", "manageable", "too_much"] },
    concernTargets: ["oiliness", "breakouts", "texture"],
    barrierFriendly: true,
    pregnancyCaution: false,
    fragranceFree: true,
    essentialOilFree: true,
    alcoholFree: true,
    textureWeight: "light",
    finish: "natural",
    intensity: "low",
    experienceLevel: "beginner",
    dayPreferred: false,
    nightPreferred: false,
    amAllowed: true,
    pmAllowed: true,
    requiresSpf: false,
    incompatibleWith: [],
    cautionNotes: ["Can be a little too cleansing for very dry skin if overused."],
    tags: ["foaming", "oily-skin", "gel-cleanser", "daily"]
  },
  {
    id: "inkey-list-salicylic-acid-cleanser",
    brand: "The Inkey List",
    productName: "Salicylic Acid Cleanser",
    fullName: "The Inkey List Salicylic Acid Cleanser",
    role: "cleanser",
    category: "cleanser_active",
    priceAUD: 22,
    size: "150ml",
    purchaseUrl: null,
    affiliateUrl: null,
    imageUrl: "/pack1/b9314b59-63a0-4058-aaba-9a7fa62ac694.png",
    keyActives: ["2% salicylic acid", "zinc compound"],
    ingredientNotes: ["active cleanser", "short-contact BHA support"],
    freeFrom: ["fragrance"],
    sensitivity: { good: ["resilient"], okay: ["moderate"], avoid: ["reactive"] },
    breakout: { good: ["frequent", "persistent", "occasional"], okay: ["rare"] },
    oiliness: { good: ["oily_tzone", "oily_all"], okay: ["balanced"], avoid: ["dry"] },
    hydration: { good: ["low"], avoid: ["high"] },
    routineTime: { good: ["easy", "manageable"], okay: ["too_much"] },
    concernTargets: ["breakouts", "oiliness", "texture"],
    barrierFriendly: false,
    pregnancyCaution: false,
    fragranceFree: true,
    essentialOilFree: true,
    alcoholFree: true,
    textureWeight: "light",
    finish: "natural",
    intensity: "moderate",
    experienceLevel: "intermediate",
    dayPreferred: false,
    nightPreferred: true,
    amAllowed: true,
    pmAllowed: true,
    requiresSpf: false,
    incompatibleWith: ["benzac-ac-2-5-gel", "paulas-choice-2-bha-liquid"],
    cautionNotes: ["Avoid stacking with multiple strong acne actives in the same routine if reactive."],
    tags: ["bha-cleanser", "oily", "acne", "active-cleanser"]
  },
  {
    id: "ordinary-glycolipid-cream-cleanser",
    brand: "The Ordinary",
    productName: "Glycolipid Cream Cleanser",
    fullName: "The Ordinary Glycolipid Cream Cleanser",
    role: "cleanser",
    category: "cleanser_gentle",
    priceAUD: 19,
    size: "150ml",
    purchaseUrl: null,
    affiliateUrl: null,
    imageUrl: "/pack1/b7a96626-ea93-49c6-bd8d-e6a73d796c21.png",
    keyActives: ["glycolipids"],
    ingredientNotes: ["soft cream cleanser", "makeup/sunscreen supportive first cleanse option"],
    freeFrom: ["fragrance", "alcohol"],
    sensitivity: { good: ["reactive", "moderate", "resilient"] },
    breakout: { good: ["rare", "occasional"], okay: ["frequent"] },
    oiliness: { good: ["dry", "balanced"], okay: ["oily_tzone"], avoid: ["oily_all"] },
    hydration: { good: ["high"], okay: ["low"] },
    routineTime: { good: ["easy", "manageable", "too_much"] },
    concernTargets: ["dryness", "barrier", "dehydration"],
    barrierFriendly: true,
    pregnancyCaution: false,
    fragranceFree: true,
    essentialOilFree: true,
    alcoholFree: true,
    textureWeight: "medium",
    finish: "natural",
    intensity: "low",
    experienceLevel: "beginner",
    dayPreferred: false,
    nightPreferred: false,
    amAllowed: true,
    pmAllowed: true,
    requiresSpf: false,
    incompatibleWith: [],
    cautionNotes: ["Best as a gentle cleanse, not a strong resurfacing product."],
    tags: ["cream-cleanser", "gentle", "dry-skin", "barrier"]
  },
  {
    id: "vanicream-gentle-facial-cleanser",
    brand: "Vanicream",
    productName: "Gentle Facial Cleanser",
    fullName: "Vanicream Gentle Facial Cleanser",
    role: "cleanser",
    category: "cleanser_gentle",
    priceAUD: 24,
    size: "237ml",
    purchaseUrl: null,
    affiliateUrl: null,
    imageUrl: "/pack1/b7a96626-ea93-49c6-bd8d-e6a73d796c21.png",
    keyActives: [],
    ingredientNotes: ["ultra-simple cleanser", "excellent reactive fallback"],
    freeFrom: ["fragrance", "dye", "lanolin", "parabens"],
    sensitivity: { good: ["reactive", "moderate", "resilient"] },
    breakout: { good: ["rare", "occasional", "frequent"], okay: ["persistent"] },
    oiliness: { good: ["dry", "balanced", "oily_tzone"], okay: ["oily_all"] },
    hydration: { good: ["high", "low"] },
    routineTime: { good: ["easy", "manageable", "too_much"] },
    concernTargets: ["barrier", "redness"],
    barrierFriendly: true,
    pregnancyCaution: false,
    fragranceFree: true,
    essentialOilFree: true,
    alcoholFree: true,
    textureWeight: "light",
    finish: "natural",
    intensity: "low",
    experienceLevel: "beginner",
    dayPreferred: false,
    nightPreferred: false,
    amAllowed: true,
    pmAllowed: true,
    requiresSpf: false,
    incompatibleWith: [],
    cautionNotes: ["Useful as the safest cleanser default for extremely sensitive users."],
    tags: ["reactive-safe", "minimal", "gentle-cleanser", "fallback"]
  },

  // MOISTURIZERS (6)
  {
    id: "neutrogena-hydro-boost-water-gel",
    brand: "Neutrogena",
    productName: "Hydro Boost Water Gel",
    fullName: "Neutrogena Hydro Boost Water Gel",
    role: "moisturizer",
    category: "moisturizer_gel",
    priceAUD: 30,
    size: "50g",
    purchaseUrl: null,
    affiliateUrl: null,
    imageUrl: "/pack1/a8f55b7f-84f2-4060-8174-fae3a7e02aab.png",
    keyActives: ["hyaluronic acid", "glycerin"],
    ingredientNotes: ["light gel hydration", "good cosmetic elegance"],
    freeFrom: [],
    sensitivity: { good: ["resilient", "moderate"], okay: ["reactive"] },
    breakout: { good: ["rare", "occasional", "frequent"], okay: ["persistent"] },
    oiliness: { good: ["oily_tzone", "oily_all", "balanced"], okay: ["dry"] },
    hydration: { good: ["low"], okay: ["high"] },
    routineTime: { good: ["easy", "manageable", "too_much"] },
    concernTargets: ["dehydration", "oiliness"],
    barrierFriendly: false,
    pregnancyCaution: false,
    fragranceFree: false,
    essentialOilFree: true,
    alcoholFree: false,
    textureWeight: "light",
    finish: "dewy",
    intensity: "low",
    experienceLevel: "beginner",
    dayPreferred: true,
    nightPreferred: true,
    amAllowed: true,
    pmAllowed: true,
    requiresSpf: false,
    incompatibleWith: [],
    cautionNotes: ["Not ideal as the default pick for highly reactive or severely dry skin."],
    tags: ["gel-moisturizer", "lightweight", "oily-friendly", "dewy"]
  },
  {
    id: "cerave-daily-moisturizing-lotion",
    brand: "CeraVe",
    productName: "Daily Moisturizing Lotion",
    fullName: "CeraVe Daily Moisturizing Lotion",
    role: "moisturizer",
    category: "moisturizer_lotion",
    priceAUD: 24,
    size: "236ml",
    purchaseUrl: null,
    affiliateUrl: null,
    imageUrl: "/pack1/b46aee69-36df-4252-bd87-dd4c08a6b197.png",
    keyActives: ["ceramides", "hyaluronic acid", "glycerin"],
    ingredientNotes: ["simple baseline lotion", "face/body crossover but reliable for face"],
    freeFrom: ["fragrance"],
    sensitivity: { good: ["reactive", "moderate", "resilient"] },
    breakout: { good: ["rare", "occasional", "frequent"], okay: ["persistent"] },
    oiliness: { good: ["balanced", "dry", "oily_tzone"], okay: ["oily_all"] },
    hydration: { good: ["high", "low"] },
    routineTime: { good: ["easy", "manageable", "too_much"] },
    concernTargets: ["dryness", "barrier", "dehydration"],
    barrierFriendly: true,
    pregnancyCaution: false,
    fragranceFree: true,
    essentialOilFree: true,
    alcoholFree: true,
    textureWeight: "medium",
    finish: "natural",
    intensity: "low",
    experienceLevel: "beginner",
    dayPreferred: true,
    nightPreferred: true,
    amAllowed: true,
    pmAllowed: true,
    requiresSpf: false,
    incompatibleWith: [],
    cautionNotes: ["Safe baseline moisturizer for many profiles."],
    tags: ["baseline", "barrier", "lotion", "all-rounder"]
  },
  {
    id: "lrp-toleriane-double-repair-moisturizer",
    brand: "La Roche-Posay",
    productName: "Toleriane Double Repair Face Moisturizer",
    fullName: "La Roche-Posay Toleriane Double Repair Face Moisturizer",
    role: "moisturizer",
    category: "moisturizer_cream",
    priceAUD: 35,
    size: "75ml",
    purchaseUrl: null,
    affiliateUrl: null,
    imageUrl: "/pack1/b46aee69-36df-4252-bd87-dd4c08a6b197.png",
    keyActives: ["ceramide-3", "niacinamide", "glycerin"],
    ingredientNotes: ["barrier-supportive cream-lotion hybrid"],
    freeFrom: ["fragrance"],
    sensitivity: { good: ["reactive", "moderate", "resilient"] },
    breakout: { good: ["rare", "occasional", "frequent"], okay: ["persistent"] },
    oiliness: { good: ["balanced", "dry", "oily_tzone"], okay: ["oily_all"] },
    hydration: { good: ["high", "low"] },
    routineTime: { good: ["easy", "manageable", "too_much"] },
    concernTargets: ["dryness", "barrier", "redness", "dehydration"],
    barrierFriendly: true,
    pregnancyCaution: false,
    fragranceFree: true,
    essentialOilFree: true,
    alcoholFree: true,
    textureWeight: "medium",
    finish: "natural",
    intensity: "low",
    experienceLevel: "beginner",
    dayPreferred: true,
    nightPreferred: true,
    amAllowed: true,
    pmAllowed: true,
    requiresSpf: false,
    incompatibleWith: [],
    cautionNotes: ["Strong default for moderate-to-reactive users needing more support than a gel."],
    tags: ["barrier-cream", "niacinamide", "reactive-safe", "medium"]
  },
  {
    id: "fab-ultra-repair-cream",
    brand: "First Aid Beauty",
    productName: "Ultra Repair Cream",
    fullName: "First Aid Beauty Ultra Repair Cream",
    role: "moisturizer",
    category: "moisturizer_cream",
    priceAUD: 42,
    size: "170g",
    purchaseUrl: null,
    affiliateUrl: null,
    imageUrl: "/pack1/b5229b96-2af6-48ea-8950-343028860ea8.png",
    keyActives: ["colloidal oatmeal", "shea butter", "ceramide support"],
    ingredientNotes: ["richer dryness-focused cream", "eczema-leaning support"],
    freeFrom: ["fragrance"],
    sensitivity: { good: ["reactive", "moderate"], okay: ["resilient"] },
    breakout: { good: ["rare", "occasional"], okay: ["frequent"], avoid: ["persistent"] },
    oiliness: { good: ["dry"], okay: ["balanced"], avoid: ["oily_tzone", "oily_all"] },
    hydration: { good: ["high"], avoid: ["low"] },
    routineTime: { good: ["easy", "manageable", "too_much"] },
    concernTargets: ["dryness", "barrier", "redness", "dehydration"],
    barrierFriendly: true,
    pregnancyCaution: false,
    fragranceFree: true,
    essentialOilFree: true,
    alcoholFree: true,
    textureWeight: "rich",
    finish: "dewy",
    intensity: "low",
    experienceLevel: "beginner",
    dayPreferred: false,
    nightPreferred: true,
    amAllowed: true,
    pmAllowed: true,
    requiresSpf: false,
    incompatibleWith: [],
    cautionNotes: ["Too rich for very oily or congestion-prone users as a default."],
    tags: ["rich-cream", "dry-skin", "barrier-repair", "oatmeal"]
  },
  {
    id: "lrp-cicaplast-baume-b5",
    brand: "La Roche-Posay",
    productName: "Cicaplast Baume B5+",
    fullName: "La Roche-Posay Cicaplast Baume B5+",
    role: "balm",
    category: "repair_balm",
    priceAUD: 26,
    size: "40ml",
    purchaseUrl: null,
    affiliateUrl: null,
    imageUrl: "/pack1/b5229b96-2af6-48ea-8950-343028860ea8.png",
    keyActives: ["panthenol", "madecassoside", "zinc", "shea butter"],
    ingredientNotes: ["repair balm", "post-irritation support", "not a universal everyday moisturizer"],
    freeFrom: ["fragrance"],
    sensitivity: { good: ["reactive", "moderate", "resilient"] },
    breakout: { good: ["rare", "occasional"], okay: ["frequent"], avoid: ["persistent"] },
    oiliness: { good: ["dry", "balanced"], okay: ["oily_tzone"], avoid: ["oily_all"] },
    hydration: { good: ["high"], okay: ["low"] },
    routineTime: { good: ["easy", "manageable"], okay: ["too_much"] },
    concernTargets: ["barrier", "redness", "dryness"],
    barrierFriendly: true,
    pregnancyCaution: false,
    fragranceFree: true,
    essentialOilFree: true,
    alcoholFree: true,
    textureWeight: "occlusive",
    finish: "glossy",
    intensity: "low",
    experienceLevel: "beginner",
    dayPreferred: false,
    nightPreferred: true,
    amAllowed: true,
    pmAllowed: true,
    requiresSpf: false,
    incompatibleWith: [],
    cautionNotes: ["Best used as a targeted repair or night-support product, not always the daily default."],
    tags: ["repair-balm", "cicaplast", "barrier", "post-irritation"]
  },
  {
    id: "aveeno-calm-restore-oat-gel-moisturizer",
    brand: "Aveeno",
    productName: "Calm + Restore Oat Gel Moisturizer",
    fullName: "Aveeno Calm + Restore Oat Gel Moisturizer",
    role: "moisturizer",
    category: "moisturizer_gel",
    priceAUD: 32,
    size: "50ml",
    purchaseUrl: null,
    affiliateUrl: null,
    imageUrl: "/pack1/a8f55b7f-84f2-4060-8174-fae3a7e02aab.png",
    keyActives: ["prebiotic oat", "feverfew", "glycerin"],
    ingredientNotes: ["reactive-skin friendly gel-cream"],
    freeFrom: ["fragrance", "alcohol"],
    sensitivity: { good: ["reactive", "moderate", "resilient"] },
    breakout: { good: ["rare", "occasional", "frequent"], okay: ["persistent"] },
    oiliness: { good: ["balanced", "oily_tzone", "dry"], okay: ["oily_all"] },
    hydration: { good: ["high", "low"] },
    routineTime: { good: ["easy", "manageable", "too_much"] },
    concernTargets: ["redness", "barrier", "dehydration"],
    barrierFriendly: true,
    pregnancyCaution: false,
    fragranceFree: true,
    essentialOilFree: true,
    alcoholFree: true,
    textureWeight: "light",
    finish: "natural",
    intensity: "low",
    experienceLevel: "beginner",
    dayPreferred: true,
    nightPreferred: true,
    amAllowed: true,
    pmAllowed: true,
    requiresSpf: false,
    incompatibleWith: [],
    cautionNotes: ["Good gel option when Hydro Boost is too fragranced or flashy."],
    tags: ["gel-cream", "reactive-safe", "oat", "barrier"]
  },

  // SUNSCREENS (4)
  {
    id: "lrp-anthelios-invisible-fluid-spf50",
    brand: "La Roche-Posay",
    productName: "Anthelios Invisible Fluid SPF50+",
    fullName: "La Roche-Posay Anthelios Invisible Fluid SPF50+",
    role: "sunscreen",
    category: "sunscreen_chemical",
    priceAUD: 33,
    size: "50ml",
    purchaseUrl: null,
    affiliateUrl: null,
    imageUrl: "/pack1/c869d2a1-20ce-4e0b-b13a-43b7a90a1450.png",
    keyActives: ["modern UV filters"],
    ingredientNotes: ["high-protection fluid", "cosmetically elegant"],
    freeFrom: [],
    sensitivity: { good: ["moderate", "resilient"], okay: ["reactive"] },
    breakout: { good: ["rare", "occasional", "frequent"], okay: ["persistent"] },
    oiliness: { good: ["oily_tzone", "oily_all", "balanced"], okay: ["dry"] },
    hydration: { good: ["low"], okay: ["high"] },
    routineTime: { good: ["easy", "manageable", "too_much"] },
    concernTargets: ["oiliness", "pigmentation", "redness"],
    barrierFriendly: true,
    pregnancyCaution: false,
    fragranceFree: false,
    essentialOilFree: true,
    alcoholFree: false,
    textureWeight: "weightless",
    finish: "natural",
    intensity: "low",
    experienceLevel: "beginner",
    dayPreferred: true,
    nightPreferred: false,
    amAllowed: true,
    pmAllowed: false,
    requiresSpf: false,
    incompatibleWith: [],
    cautionNotes: ["Patch test if highly reactive and alcohol-sensitive."],
    tags: ["spf", "lightweight", "fluid", "daily-spf"]
  },
  {
    id: "eltamd-uv-clear-spf46",
    brand: "EltaMD",
    productName: "UV Clear SPF 46",
    fullName: "EltaMD UV Clear Broad-Spectrum SPF 46",
    role: "sunscreen",
    category: "sunscreen_chemical",
    priceAUD: 65,
    size: "48g",
    purchaseUrl: null,
    affiliateUrl: null,
    imageUrl: "/pack1/c869d2a1-20ce-4e0b-b13a-43b7a90a1450.png",
    keyActives: ["zinc oxide", "niacinamide"],
    ingredientNotes: ["acne-prone favorite", "light elegant daily sunscreen"],
    freeFrom: ["fragrance"],
    sensitivity: { good: ["reactive", "moderate", "resilient"] },
    breakout: { good: ["occasional", "frequent", "persistent"], okay: ["rare"] },
    oiliness: { good: ["balanced", "oily_tzone", "oily_all"], okay: ["dry"] },
    hydration: { good: ["low"], okay: ["high"] },
    routineTime: { good: ["easy", "manageable", "too_much"] },
    concernTargets: ["breakouts", "redness", "pigmentation"],
    barrierFriendly: true,
    pregnancyCaution: false,
    fragranceFree: true,
    essentialOilFree: true,
    alcoholFree: true,
    textureWeight: "light",
    finish: "natural",
    intensity: "low",
    experienceLevel: "beginner",
    dayPreferred: true,
    nightPreferred: false,
    amAllowed: true,
    pmAllowed: false,
    requiresSpf: false,
    incompatibleWith: [],
    cautionNotes: ["Premium price tier; useful as an acne-friendly sunscreen option."],
    tags: ["spf", "acne-friendly", "niacinamide", "reactive-safe"]
  },
  {
    id: "cerave-hydrating-mineral-spf50",
    brand: "CeraVe",
    productName: "Hydrating Mineral Sunscreen SPF 50",
    fullName: "CeraVe Hydrating Mineral Sunscreen SPF 50 Face Lotion",
    role: "sunscreen",
    category: "sunscreen_mineral",
    priceAUD: 28,
    size: "75ml",
    purchaseUrl: null,
    affiliateUrl: null,
    imageUrl: "/pack1/c869d2a1-20ce-4e0b-b13a-43b7a90a1450.png",
    keyActives: ["zinc oxide", "titanium dioxide", "ceramides"],
    ingredientNotes: ["mineral option", "better for high sensitivity but heavier finish"],
    freeFrom: ["fragrance"],
    sensitivity: { good: ["reactive", "moderate"], okay: ["resilient"] },
    breakout: { good: ["rare", "occasional"], okay: ["frequent"], avoid: ["persistent"] },
    oiliness: { good: ["dry", "balanced"], okay: ["oily_tzone"], avoid: ["oily_all"] },
    hydration: { good: ["high"], okay: ["low"] },
    routineTime: { good: ["easy", "manageable"], okay: ["too_much"] },
    concernTargets: ["redness", "barrier", "pigmentation"],
    barrierFriendly: true,
    pregnancyCaution: false,
    fragranceFree: true,
    essentialOilFree: true,
    alcoholFree: true,
    textureWeight: "medium",
    finish: "dewy",
    intensity: "low",
    experienceLevel: "beginner",
    dayPreferred: true,
    nightPreferred: false,
    amAllowed: true,
    pmAllowed: false,
    requiresSpf: false,
    incompatibleWith: [],
    cautionNotes: ["White cast and heavier feel may reduce adherence for deeper skin tones or oily users."],
    tags: ["mineral-spf", "reactive-skin", "dry-skin", "zinc"]
  },
  {
    id: "beauty-of-joseon-relief-sun-spf50",
    brand: "Beauty of Joseon",
    productName: "Relief Sun SPF50+",
    fullName: "Beauty of Joseon Relief Sun: Rice + Probiotics SPF50+",
    role: "sunscreen",
    category: "sunscreen_chemical",
    priceAUD: 28,
    size: "50ml",
    purchaseUrl: null,
    affiliateUrl: null,
    imageUrl: "/pack1/d44d974f-15c7-40b3-bc98-0e3c3348696b.png",
    keyActives: ["UV filters", "rice extract", "probiotics"],
    ingredientNotes: ["hydrating elegant chemical sunscreen"],
    freeFrom: ["fragrance"],
    sensitivity: { good: ["reactive", "moderate", "resilient"] },
    breakout: { good: ["rare", "occasional", "frequent"], okay: ["persistent"] },
    oiliness: { good: ["balanced", "dry", "oily_tzone"], okay: ["oily_all"] },
    hydration: { good: ["high"], okay: ["low"] },
    routineTime: { good: ["easy", "manageable", "too_much"] },
    concernTargets: ["pigmentation", "dryness", "redness"],
    barrierFriendly: true,
    pregnancyCaution: false,
    fragranceFree: true,
    essentialOilFree: true,
    alcoholFree: true,
    textureWeight: "light",
    finish: "dewy",
    intensity: "low",
    experienceLevel: "beginner",
    dayPreferred: true,
    nightPreferred: false,
    amAllowed: true,
    pmAllowed: false,
    requiresSpf: false,
    incompatibleWith: [],
    cautionNotes: ["Useful hydrating SPF alternative to more matte fluid sunscreens."],
    tags: ["spf", "hydrating", "k-beauty", "dewy"]
  },

  // VITAMIN C (3)
  {
    id: "skinceuticals-ce-ferulic",
    brand: "SkinCeuticals",
    productName: "C E Ferulic",
    fullName: "SkinCeuticals C E Ferulic",
    role: "serum",
    category: "vitamin_c",
    priceAUD: 260,
    size: "30ml",
    purchaseUrl: null,
    affiliateUrl: null,
    imageUrl: "/pack1/2854538a-0eae-4985-8c7c-0f3a4c032956.png",
    keyActives: ["15% l-ascorbic acid", "1% vitamin e", "0.5% ferulic acid"],
    ingredientNotes: ["strong classic vitamin C format", "high efficacy but can sting"],
    freeFrom: [],
    sensitivity: { good: ["resilient"], okay: ["moderate"], avoid: ["reactive"] },
    breakout: { good: ["rare", "occasional"], okay: ["frequent"] },
    oiliness: { good: ["balanced", "dry", "oily_tzone"], okay: ["oily_all"] },
    hydration: { good: ["low"], okay: ["high"] },
    routineTime: { good: ["manageable"], okay: ["easy", "too_much"] },
    concernTargets: ["dullness", "pigmentation", "texture"],
    barrierFriendly: false,
    pregnancyCaution: false,
    fragranceFree: true,
    essentialOilFree: true,
    alcoholFree: false,
    textureWeight: "light",
    finish: "natural",
    intensity: "high",
    experienceLevel: "advanced",
    dayPreferred: true,
    nightPreferred: false,
    amAllowed: true,
    pmAllowed: true,
    requiresSpf: true,
    incompatibleWith: ["ordinary-glycolic-acid-7-toning-solution", "ordinary-retinol-0-2-squalane"],
    cautionNotes: ["Not a default pick for reactive users. Best for resilient users targeting brightening."],
    tags: ["vitamin-c", "l-ascorbic-acid", "advanced", "brightening"]
  },
  {
    id: "ordinary-ascorbyl-glucoside-12",
    brand: "The Ordinary",
    productName: "Ascorbyl Glucoside Solution 12%",
    fullName: "The Ordinary Ascorbyl Glucoside Solution 12%",
    role: "serum",
    category: "vitamin_c",
    priceAUD: 24,
    size: "30ml",
    purchaseUrl: null,
    affiliateUrl: null,
    imageUrl: "/pack1/4528d520-2095-417c-a8fa-1b43d617be7c.png",
    keyActives: ["ascorbyl glucoside"],
    ingredientNotes: ["gentler water-based vitamin C derivative"],
    freeFrom: ["fragrance", "alcohol", "oil"],
    sensitivity: { good: ["reactive", "moderate", "resilient"] },
    breakout: { good: ["rare", "occasional", "frequent"], okay: ["persistent"] },
    oiliness: { good: ["balanced", "oily_tzone", "oily_all", "dry"] },
    hydration: { good: ["low", "high"] },
    routineTime: { good: ["easy", "manageable", "too_much"] },
    concernTargets: ["dullness", "pigmentation"],
    barrierFriendly: true,
    pregnancyCaution: false,
    fragranceFree: true,
    essentialOilFree: true,
    alcoholFree: true,
    textureWeight: "light",
    finish: "natural",
    intensity: "low",
    experienceLevel: "beginner",
    dayPreferred: true,
    nightPreferred: false,
    amAllowed: true,
    pmAllowed: true,
    requiresSpf: true,
    incompatibleWith: [],
    cautionNotes: ["Gentler but usually less dramatic than pure ascorbic acid options."],
    tags: ["vitamin-c", "gentle", "beginner", "derivative"]
  },
  {
    id: "ordinary-ascorbyl-tetraisopalmitate-20",
    brand: "The Ordinary",
    productName: "Ascorbyl Tetraisopalmitate Solution 20% in Vitamin F",
    fullName: "The Ordinary Ascorbyl Tetraisopalmitate Solution 20% in Vitamin F",
    role: "serum",
    category: "vitamin_c",
    priceAUD: 31,
    size: "30ml",
    purchaseUrl: null,
    affiliateUrl: null,
    imageUrl: "/pack1/2854538a-0eae-4985-8c7c-0f3a4c032956.png",
    keyActives: ["ascorbyl tetraisopalmitate", "vitamin F lipids"],
    ingredientNotes: ["oil-soluble vitamin C derivative", "better for dry or compromised users than pure acid"],
    freeFrom: ["fragrance"],
    sensitivity: { good: ["moderate", "reactive", "resilient"] },
    breakout: { good: ["rare", "occasional"], okay: ["frequent"], avoid: ["persistent"] },
    oiliness: { good: ["dry", "balanced"], okay: ["oily_tzone"], avoid: ["oily_all"] },
    hydration: { good: ["high"], okay: ["low"] },
    routineTime: { good: ["easy", "manageable"] },
    concernTargets: ["dullness", "pigmentation", "dryness"],
    barrierFriendly: true,
    pregnancyCaution: false,
    fragranceFree: true,
    essentialOilFree: true,
    alcoholFree: true,
    textureWeight: "medium",
    finish: "dewy",
    intensity: "moderate",
    experienceLevel: "intermediate",
    dayPreferred: true,
    nightPreferred: false,
    amAllowed: true,
    pmAllowed: true,
    requiresSpf: true,
    incompatibleWith: [],
    cautionNotes: ["Can feel too emollient for oily acne-prone users."],
    tags: ["vitamin-c", "oil-soluble", "dry-skin", "brightening"]
  },

  // COPPER PEPTIDES (2)
  {
    id: "ordinary-multi-peptide-copper-peptides-1",
    brand: "The Ordinary",
    productName: "Multi-Peptide + Copper Peptides 1% Serum",
    fullName: "The Ordinary Multi-Peptide + Copper Peptides 1% Serum",
    role: "serum",
    category: "copper_peptide",
    priceAUD: 55,
    size: "30ml",
    purchaseUrl: null,
    affiliateUrl: null,
    imageUrl: "/pack1/4528d520-2095-417c-a8fa-1b43d617be7c.png",
    keyActives: ["copper peptides", "multi-peptide complex", "HA"],
    ingredientNotes: ["lighter copper peptide option", "anti-aging/support angle"],
    freeFrom: ["fragrance", "alcohol"],
    sensitivity: { good: ["reactive", "moderate", "resilient"] },
    breakout: { good: ["rare", "occasional", "frequent"], okay: ["persistent"] },
    oiliness: { good: ["balanced", "dry", "oily_tzone", "oily_all"] },
    hydration: { good: ["low", "high"] },
    routineTime: { good: ["manageable", "too_much"], okay: ["easy"] },
    concernTargets: ["redness", "barrier", "texture"],
    barrierFriendly: true,
    pregnancyCaution: false,
    fragranceFree: true,
    essentialOilFree: true,
    alcoholFree: true,
    textureWeight: "light",
    finish: "natural",
    intensity: "moderate",
    experienceLevel: "intermediate",
    dayPreferred: false,
    nightPreferred: true,
    amAllowed: true,
    pmAllowed: true,
    requiresSpf: false,
    incompatibleWith: ["skinceuticals-ce-ferulic", "ordinary-glycolic-acid-7-toning-solution"],
    cautionNotes: ["Usually best separated from direct acids in the same routine."],
    tags: ["copper-peptides", "repair", "anti-aging", "moderate"]
  },
  {
    id: "niod-cais-3-1-1",
    brand: "NIOD",
    productName: "Copper Amino Isolate Serum 3 1:1",
    fullName: "NIOD Copper Amino Isolate Serum 3 1:1",
    role: "serum",
    category: "copper_peptide",
    priceAUD: 110,
    size: "15ml",
    purchaseUrl: null,
    affiliateUrl: null,
    imageUrl: "/pack1/4528d520-2095-417c-a8fa-1b43d617be7c.png",
    keyActives: ["copper peptide complex"],
    ingredientNotes: ["premium stronger copper peptide positioning"],
    freeFrom: ["fragrance", "alcohol", "oil"],
    sensitivity: { good: ["resilient", "moderate"], okay: ["reactive"] },
    breakout: { good: ["rare", "occasional", "frequent"], okay: ["persistent"] },
    oiliness: { good: ["balanced", "dry", "oily_tzone", "oily_all"] },
    hydration: { good: ["low", "high"] },
    routineTime: { good: ["manageable", "too_much"] },
    concernTargets: ["texture", "barrier", "redness"],
    barrierFriendly: true,
    pregnancyCaution: false,
    fragranceFree: true,
    essentialOilFree: true,
    alcoholFree: true,
    textureWeight: "weightless",
    finish: "natural",
    intensity: "high",
    experienceLevel: "advanced",
    dayPreferred: false,
    nightPreferred: true,
    amAllowed: true,
    pmAllowed: true,
    requiresSpf: false,
    incompatibleWith: ["skinceuticals-ce-ferulic", "ordinary-glycolic-acid-7-toning-solution", "paulas-choice-2-bha-liquid"],
    cautionNotes: ["Advanced support product. Usually unnecessary for beginners."],
    tags: ["copper-peptides", "premium", "advanced", "repair"]
  },

  // ACNE / CONTROL (4)
  {
    id: "paulas-choice-2-bha-liquid",
    brand: "Paula's Choice",
    productName: "Skin Perfecting 2% BHA Liquid",
    fullName: "Paula's Choice Skin Perfecting 2% BHA Liquid Exfoliant",
    role: "treatment",
    category: "bha",
    priceAUD: 49,
    size: "118ml",
    purchaseUrl: null,
    affiliateUrl: null,
    imageUrl: "/pack1/5042c19f-3d0e-4d86-a5d5-1db174338b4a.png",
    keyActives: ["2% salicylic acid"],
    ingredientNotes: ["classic leave-on BHA", "stronger than cleanser-format salicylic"],
    freeFrom: ["fragrance"],
    sensitivity: { good: ["resilient"], okay: ["moderate"], avoid: ["reactive"] },
    breakout: { good: ["frequent", "persistent", "occasional"], okay: ["rare"] },
    oiliness: { good: ["oily_tzone", "oily_all", "balanced"], avoid: ["dry"] },
    hydration: { good: ["low"], avoid: ["high"] },
    routineTime: { good: ["manageable", "too_much"], okay: ["easy"] },
    concernTargets: ["breakouts", "oiliness", "texture"],
    barrierFriendly: false,
    pregnancyCaution: false,
    fragranceFree: true,
    essentialOilFree: true,
    alcoholFree: true,
    textureWeight: "weightless",
    finish: "natural",
    intensity: "high",
    experienceLevel: "advanced",
    dayPreferred: false,
    nightPreferred: true,
    amAllowed: false,
    pmAllowed: true,
    requiresSpf: true,
    incompatibleWith: ["inkey-list-salicylic-acid-cleanser", "benzac-ac-2-5-gel", "ordinary-retinol-0-2-squalane"],
    cautionNotes: ["Do not assign as a default for reactive or very dehydrated users."],
    tags: ["bha", "acne", "oil-control", "advanced"]
  },
  {
    id: "ordinary-azelaic-acid-10",
    brand: "The Ordinary",
    productName: "Azelaic Acid Suspension 10%",
    fullName: "The Ordinary Azelaic Acid Suspension 10%",
    role: "treatment",
    category: "azelaic",
    priceAUD: 21,
    size: "30ml",
    purchaseUrl: null,
    affiliateUrl: null,
    imageUrl: "/pack1/4a825ae9-c62a-4876-910a-6202fe187b40.png",
    keyActives: ["azelaic acid 10%"],
    ingredientNotes: ["redness + acne-support hybrid active"],
    freeFrom: ["fragrance", "alcohol"],
    sensitivity: { good: ["moderate", "resilient"], okay: ["reactive"] },
    breakout: { good: ["occasional", "frequent", "persistent"], okay: ["rare"] },
    oiliness: { good: ["balanced", "oily_tzone", "oily_all", "dry"] },
    hydration: { good: ["low"], okay: ["high"] },
    routineTime: { good: ["easy", "manageable", "too_much"] },
    concernTargets: ["redness", "breakouts", "texture", "pigmentation"],
    barrierFriendly: true,
    pregnancyCaution: false,
    fragranceFree: true,
    essentialOilFree: true,
    alcoholFree: true,
    textureWeight: "medium",
    finish: "natural",
    intensity: "moderate",
    experienceLevel: "intermediate",
    dayPreferred: true,
    nightPreferred: true,
    amAllowed: true,
    pmAllowed: true,
    requiresSpf: true,
    incompatibleWith: [],
    cautionNotes: ["Useful bridge active for users who need more than niacinamide but less than strong acids."],
    tags: ["azelaic", "redness", "acne", "pigment"]
  },
  {
    id: "ordinary-niacinamide-10-zinc-1",
    brand: "The Ordinary",
    productName: "Niacinamide 10% + Zinc 1%",
    fullName: "The Ordinary Niacinamide 10% + Zinc 1%",
    role: "serum",
    category: "niacinamide",
    priceAUD: 14,
    size: "30ml",
    purchaseUrl: null,
    affiliateUrl: null,
    imageUrl: "/pack1/2854538a-0eae-4985-8c7c-0f3a4c032956.png",
    keyActives: ["niacinamide 10%", "zinc 1%"],
    ingredientNotes: ["oil-control leaning serum", "not universally loved at high niacinamide"],
    freeFrom: ["fragrance", "alcohol", "oil"],
    sensitivity: { good: ["resilient", "moderate"], okay: ["reactive"] },
    breakout: { good: ["occasional", "frequent", "persistent"], okay: ["rare"] },
    oiliness: { good: ["oily_tzone", "oily_all", "balanced"], avoid: ["dry"] },
    hydration: { good: ["low"], okay: ["high"] },
    routineTime: { good: ["easy", "manageable", "too_much"] },
    concernTargets: ["oiliness", "breakouts", "redness"],
    barrierFriendly: true,
    pregnancyCaution: false,
    fragranceFree: true,
    essentialOilFree: true,
    alcoholFree: true,
    textureWeight: "light",
    finish: "natural",
    intensity: "moderate",
    experienceLevel: "beginner",
    dayPreferred: true,
    nightPreferred: true,
    amAllowed: true,
    pmAllowed: true,
    requiresSpf: false,
    incompatibleWith: [],
    cautionNotes: ["High niacinamide can irritate some reactive users despite being marketed as gentle."],
    tags: ["niacinamide", "oil-control", "budget", "serum"]
  },
  {
    id: "benzac-ac-2-5-gel",
    brand: "Benzac",
    productName: "AC 2.5% Benzoyl Peroxide Gel",
    fullName: "Benzac AC 2.5% Benzoyl Peroxide Gel",
    role: "treatment",
    category: "benzoyl_peroxide",
    priceAUD: 18,
    size: "60g",
    purchaseUrl: null,
    affiliateUrl: null,
    imageUrl: "/pack1/5042c19f-3d0e-4d86-a5d5-1db174338b4a.png",
    keyActives: ["benzoyl peroxide 2.5%"],
    ingredientNotes: ["strong acne-directed treatment", "drying but effective"],
    freeFrom: [],
    sensitivity: { good: ["resilient"], okay: ["moderate"], avoid: ["reactive"] },
    breakout: { good: ["frequent", "persistent"], okay: ["occasional"], avoid: ["rare"] },
    oiliness: { good: ["oily_tzone", "oily_all", "balanced"], avoid: ["dry"] },
    hydration: { good: ["low"], avoid: ["high"] },
    routineTime: { good: ["manageable", "too_much"], okay: ["easy"] },
    concernTargets: ["breakouts"],
    barrierFriendly: false,
    pregnancyCaution: false,
    fragranceFree: false,
    essentialOilFree: true,
    alcoholFree: false,
    textureWeight: "medium",
    finish: "natural",
    intensity: "high",
    experienceLevel: "advanced",
    dayPreferred: false,
    nightPreferred: true,
    amAllowed: true,
    pmAllowed: true,
    requiresSpf: true,
    incompatibleWith: ["paulas-choice-2-bha-liquid", "ordinary-glycolic-acid-7-toning-solution", "ordinary-retinol-0-2-squalane"],
    cautionNotes: ["Use carefully; high irritation potential when layered aggressively."],
    tags: ["benzoyl-peroxide", "acne", "strong", "spot-treatment"]
  },

  // EXFOLIATION (2)
  {
    id: "ordinary-glycolic-acid-7-toning-solution",
    brand: "The Ordinary",
    productName: "Glycolic Acid 7% Toning Solution",
    fullName: "The Ordinary Glycolic Acid 7% Toning Solution",
    role: "treatment",
    category: "aha",
    priceAUD: 22,
    size: "240ml",
    purchaseUrl: null,
    affiliateUrl: null,
    imageUrl: "/pack1/4a825ae9-c62a-4876-910a-6202fe187b40.png",
    keyActives: ["glycolic acid 7%"],
    ingredientNotes: ["stronger resurfacing AHA", "good for texture and dullness, not default for reactive users"],
    freeFrom: ["oil"],
    sensitivity: { good: ["resilient"], okay: ["moderate"], avoid: ["reactive"] },
    breakout: { good: ["rare", "occasional"], okay: ["frequent"] },
    oiliness: { good: ["balanced", "oily_tzone"], okay: ["dry", "oily_all"] },
    hydration: { good: ["low"], avoid: ["high"] },
    routineTime: { good: ["manageable", "too_much"], okay: ["easy"] },
    concernTargets: ["texture", "dullness", "pigmentation"],
    barrierFriendly: false,
    pregnancyCaution: false,
    fragranceFree: false,
    essentialOilFree: true,
    alcoholFree: true,
    textureWeight: "weightless",
    finish: "natural",
    intensity: "high",
    experienceLevel: "advanced",
    dayPreferred: false,
    nightPreferred: true,
    amAllowed: false,
    pmAllowed: true,
    requiresSpf: true,
    incompatibleWith: ["skinceuticals-ce-ferulic", "niod-cais-3-1-1", "ordinary-retinol-0-2-squalane", "benzac-ac-2-5-gel"],
    cautionNotes: ["Direct-acid product. Should be held back for resilient or experienced users."],
    tags: ["aha", "glycolic", "texture", "advanced"]
  },
  {
    id: "ordinary-lactic-acid-5-ha",
    brand: "The Ordinary",
    productName: "Lactic Acid 5% + HA",
    fullName: "The Ordinary Lactic Acid 5% + HA",
    role: "treatment",
    category: "aha",
    priceAUD: 16,
    size: "30ml",
    purchaseUrl: null,
    affiliateUrl: null,
    imageUrl: "/pack1/4a825ae9-c62a-4876-910a-6202fe187b40.png",
    keyActives: ["lactic acid 5%", "hyaluronic acid"],
    ingredientNotes: ["gentler AHA entry point", "better beginner resurfacing option"],
    freeFrom: ["fragrance", "alcohol"],
    sensitivity: { good: ["moderate", "resilient"], okay: ["reactive"] },
    breakout: { good: ["rare", "occasional"], okay: ["frequent"] },
    oiliness: { good: ["dry", "balanced", "oily_tzone"], okay: ["oily_all"] },
    hydration: { good: ["low"], okay: ["high"] },
    routineTime: { good: ["easy", "manageable"], okay: ["too_much"] },
    concernTargets: ["texture", "dullness"],
    barrierFriendly: false,
    pregnancyCaution: false,
    fragranceFree: true,
    essentialOilFree: true,
    alcoholFree: true,
    textureWeight: "light",
    finish: "natural",
    intensity: "moderate",
    experienceLevel: "intermediate",
    dayPreferred: false,
    nightPreferred: true,
    amAllowed: false,
    pmAllowed: true,
    requiresSpf: true,
    incompatibleWith: ["ordinary-retinol-0-2-squalane", "benzac-ac-2-5-gel"],
    cautionNotes: ["Better AHA starter than glycolic for moderate users."],
    tags: ["aha", "lactic", "beginner-friendly", "texture"]
  },

  // RETINOIDS (2)
  {
    id: "ordinary-retinol-0-2-squalane",
    brand: "The Ordinary",
    productName: "Retinol 0.2% in Squalane",
    fullName: "The Ordinary Retinol 0.2% in Squalane",
    role: "treatment",
    category: "retinoid",
    priceAUD: 14,
    size: "30ml",
    purchaseUrl: null,
    affiliateUrl: null,
    imageUrl: "/pack1/5042c19f-3d0e-4d86-a5d5-1db174338b4a.png",
    keyActives: ["retinol 0.2%", "squalane"],
    ingredientNotes: ["beginner retinol", "oily users may dislike oily base"],
    freeFrom: ["fragrance", "alcohol"],
    sensitivity: { good: ["resilient", "moderate"], avoid: ["reactive"] },
    breakout: { good: ["rare", "occasional", "frequent"], okay: ["persistent"] },
    oiliness: { good: ["dry", "balanced"], okay: ["oily_tzone"], avoid: ["oily_all"] },
    hydration: { good: ["low"], okay: ["high"] },
    routineTime: { good: ["manageable"], okay: ["easy", "too_much"] },
    concernTargets: ["texture", "breakouts", "pigmentation"],
    barrierFriendly: false,
    pregnancyCaution: true,
    fragranceFree: true,
    essentialOilFree: true,
    alcoholFree: true,
    textureWeight: "medium",
    finish: "dewy",
    intensity: "moderate",
    experienceLevel: "intermediate",
    dayPreferred: false,
    nightPreferred: true,
    amAllowed: false,
    pmAllowed: true,
    requiresSpf: true,
    incompatibleWith: ["ordinary-glycolic-acid-7-toning-solution", "paulas-choice-2-bha-liquid", "benzac-ac-2-5-gel"],
    cautionNotes: ["Retinoid caution. Avoid during pregnancy unless medically cleared."],
    tags: ["retinoid", "beginner", "night", "texture"]
  },
  {
    id: "ordinary-granactive-retinoid-2-emulsion",
    brand: "The Ordinary",
    productName: "Granactive Retinoid 2% Emulsion",
    fullName: "The Ordinary Granactive Retinoid 2% Emulsion",
    role: "treatment",
    category: "retinoid",
    priceAUD: 22,
    size: "30ml",
    purchaseUrl: null,
    affiliateUrl: null,
    imageUrl: "/pack1/4a825ae9-c62a-4876-910a-6202fe187b40.png",
    keyActives: ["granactive retinoid 2%"],
    ingredientNotes: ["mid-strength retinoid option", "clean bridge between beginner and strong retinoid usage"],
    freeFrom: ["fragrance", "alcohol"],
    sensitivity: { good: ["moderate", "resilient"], avoid: ["reactive"] },
    breakout: { good: ["occasional", "frequent", "persistent"], okay: ["rare"] },
    oiliness: { good: ["balanced", "dry", "oily_tzone"], okay: ["oily_all"] },
    hydration: { good: ["low"], okay: ["high"] },
    routineTime: { good: ["manageable", "too_much"] },
    concernTargets: ["texture", "breakouts", "pigmentation"],
    barrierFriendly: false,
    pregnancyCaution: true,
    fragranceFree: true,
    essentialOilFree: true,
    alcoholFree: true,
    textureWeight: "light",
    finish: "natural",
    intensity: "high",
    experienceLevel: "advanced",
    dayPreferred: false,
    nightPreferred: true,
    amAllowed: false,
    pmAllowed: true,
    requiresSpf: true,
    incompatibleWith: ["ordinary-glycolic-acid-7-toning-solution", "paulas-choice-2-bha-liquid", "benzac-ac-2-5-gel"],
    cautionNotes: ["Advanced retinoid lane. Do not assign to reactive or absolute beginners."],
    tags: ["retinoid", "advanced", "night", "acne-texture"]
  },

  // SUPPORT (4)
  {
    id: "ordinary-hyaluronic-acid-2-b5",
    brand: "The Ordinary",
    productName: "Hyaluronic Acid 2% + B5",
    fullName: "The Ordinary Hyaluronic Acid 2% + B5",
    role: "support",
    category: "hydration_support",
    priceAUD: 16,
    size: "30ml",
    purchaseUrl: null,
    affiliateUrl: null,
    imageUrl: "/pack1/4528d520-2095-417c-a8fa-1b43d617be7c.png",
    keyActives: ["hyaluronic acid", "panthenol"],
    ingredientNotes: ["straight hydration support serum"],
    freeFrom: ["fragrance", "alcohol", "oil"],
    sensitivity: { good: ["reactive", "moderate", "resilient"] },
    breakout: { good: ["rare", "occasional", "frequent", "persistent"] },
    oiliness: { good: ["dry", "balanced", "oily_tzone", "oily_all"] },
    hydration: { good: ["high"], okay: ["low"] },
    routineTime: { good: ["easy", "manageable", "too_much"] },
    concernTargets: ["dehydration", "dryness", "barrier"],
    barrierFriendly: true,
    pregnancyCaution: false,
    fragranceFree: true,
    essentialOilFree: true,
    alcoholFree: true,
    textureWeight: "light",
    finish: "natural",
    intensity: "low",
    experienceLevel: "beginner",
    dayPreferred: true,
    nightPreferred: true,
    amAllowed: true,
    pmAllowed: true,
    requiresSpf: false,
    incompatibleWith: [],
    cautionNotes: ["Hydration helper, not a standalone fix for barrier damage."],
    tags: ["hydration", "ha", "panthenol", "support"]
  },
  {
    id: "ordinary-100-squalane",
    brand: "The Ordinary",
    productName: "100% Plant-Derived Squalane",
    fullName: "The Ordinary 100% Plant-Derived Squalane",
    role: "support",
    category: "face_oil",
    priceAUD: 18,
    size: "30ml",
    purchaseUrl: null,
    affiliateUrl: null,
    imageUrl: "/pack1/4528d520-2095-417c-a8fa-1b43d617be7c.png",
    keyActives: ["squalane"],
    ingredientNotes: ["simple emollient support oil", "best for dryness support not oily defaults"],
    freeFrom: ["fragrance", "alcohol", "water"],
    sensitivity: { good: ["reactive", "moderate", "resilient"] },
    breakout: { good: ["rare", "occasional"], okay: ["frequent"], avoid: ["persistent"] },
    oiliness: { good: ["dry", "balanced"], okay: ["oily_tzone"], avoid: ["oily_all"] },
    hydration: { good: ["high"], okay: ["low"] },
    routineTime: { good: ["easy", "manageable", "too_much"] },
    concernTargets: ["dryness", "barrier", "dehydration"],
    barrierFriendly: true,
    pregnancyCaution: false,
    fragranceFree: true,
    essentialOilFree: true,
    alcoholFree: true,
    textureWeight: "rich",
    finish: "glossy",
    intensity: "low",
    experienceLevel: "beginner",
    dayPreferred: false,
    nightPreferred: true,
    amAllowed: true,
    pmAllowed: true,
    requiresSpf: false,
    incompatibleWith: [],
    cautionNotes: ["Usually better as a PM add-on for dry users than a universal daytime pick."],
    tags: ["squalane", "oil", "dryness", "barrier"]
  },
  {
    id: "dr-jart-cicapair-tiger-grass-serum",
    brand: "Dr. Jart+",
    productName: "Cicapair Tiger Grass Serum",
    fullName: "Dr. Jart+ Cicapair Tiger Grass Serum",
    role: "support",
    category: "calming_support",
    priceAUD: 68,
    size: "30ml",
    purchaseUrl: null,
    affiliateUrl: null,
    imageUrl: "/pack1/f333dce4-2eec-4a0c-b64b-ce3445dcace7.png",
    keyActives: ["centella asiatica", "soothing complex"],
    ingredientNotes: ["redness-calming support lane"],
    freeFrom: [],
    sensitivity: { good: ["reactive", "moderate"], okay: ["resilient"] },
    breakout: { good: ["rare", "occasional", "frequent"], okay: ["persistent"] },
    oiliness: { good: ["balanced", "dry", "oily_tzone"], okay: ["oily_all"] },
    hydration: { good: ["high", "low"] },
    routineTime: { good: ["easy", "manageable", "too_much"] },
    concernTargets: ["redness", "barrier"],
    barrierFriendly: true,
    pregnancyCaution: false,
    fragranceFree: false,
    essentialOilFree: false,
    alcoholFree: false,
    textureWeight: "light",
    finish: "natural",
    intensity: "low",
    experienceLevel: "beginner",
    dayPreferred: true,
    nightPreferred: true,
    amAllowed: true,
    pmAllowed: true,
    requiresSpf: false,
    incompatibleWith: [],
    cautionNotes: ["Calming concept is strong, but fragrance sensitivity should be considered."],
    tags: ["centella", "redness", "calming", "support"]
  },
  {
    id: "inkey-list-ceramide-serum",
    brand: "The Inkey List",
    productName: "Ceramide Serum",
    fullName: "The Inkey List Ceramide Serum",
    role: "support",
    category: "barrier_support",
    priceAUD: 24,
    size: "30ml",
    purchaseUrl: null,
    affiliateUrl: null,
    imageUrl: "/pack1/f333dce4-2eec-4a0c-b64b-ce3445dcace7.png",
    keyActives: ["multi-ceramide complex", "hyaluronic acid"],
    ingredientNotes: ["barrier support serum", "good bridge between active use and comfort"],
    freeFrom: ["fragrance", "alcohol"],
    sensitivity: { good: ["reactive", "moderate", "resilient"] },
    breakout: { good: ["rare", "occasional", "frequent"], okay: ["persistent"] },
    oiliness: { good: ["dry", "balanced", "oily_tzone"], okay: ["oily_all"] },
    hydration: { good: ["high", "low"] },
    routineTime: { good: ["easy", "manageable", "too_much"] },
    concernTargets: ["barrier", "dryness", "dehydration", "redness"],
    barrierFriendly: true,
    pregnancyCaution: false,
    fragranceFree: true,
    essentialOilFree: true,
    alcoholFree: true,
    textureWeight: "light",
    finish: "natural",
    intensity: "low",
    experienceLevel: "beginner",
    dayPreferred: true,
    nightPreferred: true,
    amAllowed: true,
    pmAllowed: true,
    requiresSpf: false,
    incompatibleWith: [],
    cautionNotes: ["Useful fallback support product when actives are restricted."],
    tags: ["ceramides", "barrier", "support", "repair"]
  }
];
