/**
 * Sprint D10: Product Catalog (Simplified)
 * Real structured product data for skincare routine steps
 */

import type { CatalogProduct } from "./types";

export const PRODUCT_CATALOG: CatalogProduct[] = [
  // CLEANSER
  {
    id: "cerave_foaming_cleanser",
    brand: "CeraVe",
    name: "Foaming Facial Cleanser",
    stepType: "cleanse",
    price: 15,
    tier: "budget",
    roleLabel: "Oil control",
    skinTargets: ["oil", "acne"],
    texture: "foam",
    finish: "natural",
    ageOptimized: "universal",
    keyIngredients: ["ceramides", "hyaluronic_acid", "niacinamide"],
    avoidanceFlags: [],
  },
  {
    id: "lrp_toleriane_cleanser",
    brand: "La Roche-Posay",
    name: "Toleriane Hydrating Cleanser",
    stepType: "cleanse",
    price: 24,
    tier: "core",
    roleLabel: "Barrier-safe",
    skinTargets: ["dry", "sensitivity", "barrier"],
    texture: "cream",
    finish: "natural",
    ageOptimized: "universal",
    keyIngredients: ["ceramides", "niacinamide", "glycerin"],
    avoidanceFlags: [],
  },
  {
    id: "krave_matcha_cleanser",
    brand: "Krave Beauty",
    name: "Matcha Hemp Hydrating Cleanser",
    stepType: "cleanse",
    price: 28,
    tier: "premium",
    roleLabel: "Low irritation",
    skinTargets: ["sensitivity", "barrier"],
    texture: "gel",
    finish: "natural",
    ageOptimized: "universal",
    keyIngredients: ["matcha", "hemp_seed_oil", "glycerin"],
    avoidanceFlags: ["essential_oils"],
  },

  // NIACINAMIDE
  {
    id: "to_niacinamide",
    brand: "The Ordinary",
    name: "Niacinamide 10% + Zinc",
    stepType: "niacinamide",
    price: 6,
    tier: "budget",
    roleLabel: "Breakout control",
    skinTargets: ["acne", "oil"],
    texture: "serum",
    finish: "natural",
    ageOptimized: "youth",
    keyIngredients: ["niacinamide", "zinc"],
    avoidanceFlags: [],
  },
  {
    id: "paulas_niacinamide",
    brand: "Paula's Choice",
    name: "10% Niacinamide Booster",
    stepType: "niacinamide",
    price: 29,
    tier: "core",
    roleLabel: "Pore refinement",
    skinTargets: ["oil", "texture"],
    texture: "serum",
    finish: "natural",
    ageOptimized: "universal",
    keyIngredients: ["niacinamide", "hyaluronic_acid"],
    avoidanceFlags: [],
  },
  {
    id: "glossier_niacinamide",
    brand: "Glossier",
    name: "Super Pure Serum",
    stepType: "niacinamide",
    price: 32,
    tier: "premium",
    roleLabel: "Gentle balancing",
    skinTargets: ["sensitivity", "redness"],
    texture: "serum",
    finish: "natural",
    ageOptimized: "prevention",
    keyIngredients: ["niacinamide", "zinc"],
    avoidanceFlags: [],
  },

  // MOISTURIZER
  {
    id: "cerave_moisturizer",
    brand: "CeraVe",
    name: "Daily Moisturizing Lotion",
    stepType: "moisturize",
    price: 16,
    tier: "budget",
    roleLabel: "Barrier restore",
    skinTargets: ["dry", "barrier"],
    texture: "lotion",
    finish: "natural",
    ageOptimized: "universal",
    keyIngredients: ["ceramides", "hyaluronic_acid", "glycerin"],
    avoidanceFlags: [],
  },
  {
    id: "lrp_double_repair",
    brand: "La Roche-Posay",
    name: "Toleriane Double Repair Moisturizer",
    stepType: "moisturize",
    price: 22,
    tier: "core",
    roleLabel: "Balanced hydration",
    skinTargets: ["dry", "normal"],
    texture: "cream",
    finish: "satin",
    ageOptimized: "universal",
    keyIngredients: ["ceramides", "niacinamide", "glycerin"],
    avoidanceFlags: [],
  },
  {
    id: "first_aid_ultra_repair",
    brand: "First Aid Beauty",
    name: "Ultra Repair Cream",
    stepType: "moisturize",
    price: 34,
    tier: "premium",
    roleLabel: "Intense barrier repair",
    skinTargets: ["barrier", "sensitivity"],
    texture: "cream",
    finish: "dewy",
    ageOptimized: "mature",
    keyIngredients: ["colloidal_oatmeal", "ceramides", "shea_butter"],
    avoidanceFlags: ["fragrance"],
  },

  // SPF
  {
    id: "neutrogena_spf",
    brand: "Neutrogena",
    name: "Ultra Sheer SPF 50",
    stepType: "spf",
    price: 12,
    tier: "budget",
    roleLabel: "Lightweight SPF",
    skinTargets: ["all"],
    texture: "lotion",
    finish: "matte",
    ageOptimized: "universal",
    keyIngredients: ["avobenzone", "homosalate", "octisalate"],
    avoidanceFlags: ["fragrance", "alcohol"],
  },
  {
    id: "lrp_anthelios",
    brand: "La Roche-Posay",
    name: "Anthelios Invisible Fluid SPF 50+",
    stepType: "spf",
    price: 30,
    tier: "core",
    roleLabel: "Daily protection",
    skinTargets: ["all"],
    texture: "lotion",
    finish: "natural",
    ageOptimized: "universal",
    keyIngredients: ["mexoryl_xl", "mexoryl_sx", "tinosorb_s"],
    avoidanceFlags: ["alcohol"],
  },
  {
    id: "elta_md_uv_clear",
    brand: "EltaMD",
    name: "UV Clear SPF 46",
    stepType: "spf",
    price: 39,
    tier: "premium",
    roleLabel: "Acne-safe SPF",
    skinTargets: ["acne", "sensitivity"],
    texture: "lotion",
    finish: "matte",
    ageOptimized: "universal",
    keyIngredients: ["zinc_oxide", "niacinamide", "hyaluronic_acid"],
    avoidanceFlags: [],
  },

  // SALICYLIC ACID
  {
    id: "cerave_sa_cleanser",
    brand: "CeraVe",
    name: "SA Cleanser",
    stepType: "salicylic",
    price: 14,
    tier: "budget",
    roleLabel: "Exfoliating cleanse",
    skinTargets: ["acne", "texture"],
    texture: "gel",
    finish: "natural",
    ageOptimized: "youth",
    keyIngredients: ["salicylic_acid", "ceramides", "niacinamide"],
    avoidanceFlags: [],
  },
  {
    id: "paulas_bha",
    brand: "Paula's Choice",
    name: "2% BHA Liquid Exfoliant",
    stepType: "salicylic",
    price: 35,
    tier: "core",
    roleLabel: "Pore clearing",
    skinTargets: ["acne", "oil"],
    texture: "serum",
    finish: "natural",
    ageOptimized: "prevention",
    keyIngredients: ["salicylic_acid", "green_tea"],
    avoidanceFlags: ["alcohol"],
  },
  {
    id: "cosrx_bha",
    brand: "COSRX",
    name: "BHA Blackhead Power Liquid",
    stepType: "salicylic",
    price: 25,
    tier: "premium",
    roleLabel: "Gentle exfoliation",
    skinTargets: ["sensitivity", "texture"],
    texture: "serum",
    finish: "natural",
    ageOptimized: "universal",
    keyIngredients: ["salicylic_acid", "niacinamide", "hyaluronic_acid"],
    avoidanceFlags: [],
  },

  // RETINOID
  {
    id: "to_retinol",
    brand: "The Ordinary",
    name: "Retinol 0.2% in Squalane",
    stepType: "retinoid",
    price: 9,
    tier: "budget",
    roleLabel: "Entry retinol",
    skinTargets: ["acne", "aging"],
    texture: "serum",
    finish: "natural",
    ageOptimized: "prevention",
    keyIngredients: ["retinol", "squalane"],
    avoidanceFlags: [],
  },
  {
    id: "paulas_retinol",
    brand: "Paula's Choice",
    name: "Clinical 1% Retinol",
    stepType: "retinoid",
    price: 58,
    tier: "core",
    roleLabel: "Advanced treatment",
    skinTargets: ["aging", "texture"],
    texture: "cream",
    finish: "satin",
    ageOptimized: "mature",
    keyIngredients: ["retinol", "peptides", "niacinamide"],
    avoidanceFlags: [],
  },
  {
    id: "medik8_crystal",
    brand: "Medik8",
    name: "Crystal Retinal",
    stepType: "retinoid",
    price: 75,
    tier: "premium",
    roleLabel: "Low irritation retinoid",
    skinTargets: ["sensitivity", "aging"],
    texture: "cream",
    finish: "dewy",
    ageOptimized: "mature",
    keyIngredients: ["retinaldehyde", "vitamin_e", "hyaluronic_acid"],
    avoidanceFlags: [],
  },

  // AZELAIC ACID
  {
    id: "to_azelaic",
    brand: "The Ordinary",
    name: "Azelaic Acid 10%",
    stepType: "azelaic",
    price: 9,
    tier: "budget",
    roleLabel: "Gentle brightening",
    skinTargets: ["redness", "sensitivity", "texture"],
    texture: "cream",
    finish: "natural",
    ageOptimized: "universal",
    keyIngredients: ["azelaic_acid"],
    avoidanceFlags: [],
  },
  {
    id: "paulas_azelaic",
    brand: "Paula's Choice",
    name: "10% Azelaic Acid Booster",
    stepType: "azelaic",
    price: 38,
    tier: "core",
    roleLabel: "Calm redness",
    skinTargets: ["redness", "sensitivity"],
    texture: "gel",
    finish: "natural",
    ageOptimized: "universal",
    keyIngredients: ["azelaic_acid", "salicylic_acid"],
    avoidanceFlags: [],
  },

  // BENZOYL PEROXIDE
  {
    id: "cerave_bpo",
    brand: "CeraVe",
    name: "Acne Foaming Cream Cleanser 4% BP",
    stepType: "benzoyl",
    price: 16,
    tier: "budget",
    roleLabel: "Spot treatment",
    skinTargets: ["acne"],
    texture: "cream",
    finish: "natural",
    ageOptimized: "youth",
    keyIngredients: ["benzoyl_peroxide", "niacinamide", "ceramides"],
    avoidanceFlags: [],
  },
  {
    id: "paulas_bpo",
    brand: "Paula's Choice",
    name: "CLEAR Regular Strength 2.5% BP",
    stepType: "benzoyl",
    price: 24,
    tier: "core",
    roleLabel: "Acne treatment",
    skinTargets: ["acne"],
    texture: "lotion",
    finish: "natural",
    ageOptimized: "youth",
    keyIngredients: ["benzoyl_peroxide"],
    avoidanceFlags: [],
  },

  // BARRIER REPAIR
  {
    id: "lrp_cicaplast",
    brand: "La Roche-Posay",
    name: "Cicaplast Baume B5",
    stepType: "barrier_repair",
    price: 15,
    tier: "budget",
    roleLabel: "Barrier repair",
    skinTargets: ["barrier", "sensitivity"],
    texture: "balm",
    finish: "dewy",
    ageOptimized: "universal",
    keyIngredients: ["panthenol", "madecassoside", "copper_zinc"],
    avoidanceFlags: [],
  },
  {
    id: "soon_jung_balm",
    brand: "Etude House",
    name: "Soon Jung 2x Barrier Intensive Cream",
    stepType: "barrier_repair",
    price: 18,
    tier: "core",
    roleLabel: "Intense repair",
    skinTargets: ["barrier", "sensitivity"],
    texture: "cream",
    finish: "satin",
    ageOptimized: "universal",
    keyIngredients: ["panthenol", "madecassoside", "ceramides"],
    avoidanceFlags: [],
  },

  // HYDRATE
  {
    id: "hada_labo_lotion",
    brand: "Hada Labo",
    name: "Gokujyun Premium Lotion",
    stepType: "hydrate",
    price: 14,
    tier: "budget",
    roleLabel: "Deep hydration",
    skinTargets: ["dry", "all"],
    texture: "lotion",
    finish: "dewy",
    ageOptimized: "universal",
    keyIngredients: ["hyaluronic_acid", "glycerin"],
    avoidanceFlags: [],
  },
  {
    id: "cosrx_snail_essence",
    brand: "COSRX",
    name: "Advanced Snail 96 Mucin Power Essence",
    stepType: "hydrate",
    price: 25,
    tier: "core",
    roleLabel: "Hydration boost",
    skinTargets: ["dry", "barrier"],
    texture: "serum",
    finish: "dewy",
    ageOptimized: "universal",
    keyIngredients: ["snail_mucin", "hyaluronic_acid"],
    avoidanceFlags: [],
  },

  // OIL CLEANSE
  {
    id: "dhc_oil_cleanser",
    brand: "DHC",
    name: "Deep Cleansing Oil",
    stepType: "oil_cleanse",
    price: 28,
    tier: "budget",
    roleLabel: "Makeup removal",
    skinTargets: ["all"],
    texture: "oil",
    finish: "natural",
    ageOptimized: "universal",
    keyIngredients: ["olive_oil", "vitamin_e"],
    avoidanceFlags: [],
  },
  {
    id: "banila_clean_it",
    brand: "Banila Co",
    name: "Clean It Zero Cleansing Balm",
    stepType: "oil_cleanse",
    price: 18,
    tier: "core",
    roleLabel: "First cleanse",
    skinTargets: ["all"],
    texture: "balm",
    finish: "natural",
    ageOptimized: "universal",
    keyIngredients: ["mineral_oil", "vitamin_c"],
    avoidanceFlags: ["fragrance"],
  },

  // OCCLUSIVE
  {
    id: "cerave_healing_ointment",
    brand: "CeraVe",
    name: "Healing Ointment",
    stepType: "occlusive",
    price: 14,
    tier: "budget",
    roleLabel: "Lock in moisture",
    skinTargets: ["dry", "barrier"],
    texture: "balm",
    finish: "dewy",
    ageOptimized: "universal",
    keyIngredients: ["petrolatum", "ceramides", "hyaluronic_acid"],
    avoidanceFlags: [],
  },
  {
    id: "aquaphor_healing",
    brand: "Aquaphor",
    name: "Healing Ointment",
    stepType: "occlusive",
    price: 15,
    tier: "core",
    roleLabel: "Seal barrier",
    skinTargets: ["dry", "barrier"],
    texture: "balm",
    finish: "dewy",
    ageOptimized: "universal",
    keyIngredients: ["petrolatum", "panthenol", "glycerin"],
    avoidanceFlags: [],
  },
];

/**
 * Get all products
 */
export function getAllProducts() {
  return PRODUCT_CATALOG;
}

/**
 * Get product by ID
 */
export function getProductById(id: string) {
  return PRODUCT_CATALOG.find((p) => p.id === id);
}

/**
 * Get products by step type
 */
export function getProductsByStepType(stepType: string) {
  return PRODUCT_CATALOG.filter((p) => p.stepType === stepType);
}
